name: Run Newman Tests

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: write 

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci --force

      - name: Install Newman
        run: npm install -g newman --force

      - name: Run Postman Collection and generate HTML report
        run: |
          newman run Alemx.postman_collection.json \
            -r cli,html \
            --reporter-html-export newman-report.html
        continue-on-error: true

      - name: Publish report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          keep_files: true
          force_orphan: true
